### ISSUE TITLE
Puppet run dies.

### ISSUE THREAD

**Issue by karolisc** [Security-Onion-Solutions/securityonion-rule-update#1]
Hi Doug,

The other day I have puppetized the rule-update script. 
On the sensors due to this "unmaned system" [sleep](https://github.com/Security-Onion-Solutions/securityonion-rule-update/blob/master/usr/bin/rule-update#L213-L217) puppet run dies (timeout). 
I have put an band aid by changing sleep to 2 minutes although it is unacceptable for configuration manager to run so long.
Possible fix could be that install script detects server install and puts rule-update cronjob 5 mins earlier?

p.s.
Other configuration managers should suffer from it too.

Karolis

**Comment by dougburks** [comment]
Hi Karolis,

Since you're running puppet, you could do something similar to what we do
with salt. You could have puppet remove the default rule-update mechanism
and replace it with your own custom rule update mechanism. Your custom rule
update mechanism might then leverage file copy features built into puppet
itself, totally eliminating the need for /usr/bin/rule-update and its
default sleep value.

On Friday, April 3, 2015, karolisc notifications@github.com wrote:

> Hi Doug,
> 
> The other day I have puppetized the rule-update script.
> On the sensors due to this "unmaned system" sleep
> https://github.com/Security-Onion-Solutions/securityonion-rule-update/blob/master/usr/bin/rule-update#L213-L217
> puppet run dies (timeout).
> I have put an band aid by changing sleep to 2 minutes although it is
> unacceptable for configuration manager to run so long.
> Possible fix could be that install script detects server install and puts
> rule-update cronjob 5 mins earlier?
> 
> p.s.
> Other configuration managers should suffer from it too.
> 
> Karolis
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Security-Onion-Solutions/securityonion-rule-update/issues/1
> .

## 

Doug Burks
Need Security Onion Training or Commercial Support?
http://securityonionsolutions.com
